---

- name: install glusterfs repository
  yum: name=centos-release-gluster state=present

- name: install glusterfs
  yum: name=glusterfs-server state=present

- name: start glusterd
  service:
    name: glusterd
    enabled: true
    state: started

# {%- if peers.append(hostvars[host]['ansible_' + hostvars[host]['gluster_interface']]['ipv4']['address']) -%}
- name: "compute peers for each host"
  set_fact:
    hosts: |
      {%- set peers=[] -%}
      {%- for host in groups[gluster_peers_group] -%}
          {%- if host != ansible_hostname -%}
            {%- if peers.append(host) -%}
            {%- endif -%}
          {%- endif -%}
      {%- endfor -%}
      {{ peers }}

- name: "probe peers {{ hostvars }}"
  command: "gluster peer probe {{ item }}"
  with_items: hosts
  when: install_gluster
  register: command_result
  failed_when: "command_result.rc != 0 and command_result.rc != 1"
